### ISSUE TITLE
Failed to download yue: There is no build for your Node.js version (error 404).

### ISSUE THREAD

**Issue by ledlamp** [yue/node-gui#23] opened 2018-12-19 04:50 UTC
```
$ npm i gui

> gui@0.5.0 postinstall /Users/me/Desktop/jzz/node_modules/gui
> node install.js

Failed to download yue: There is no build for your Node.js version (error 404).
npm WARN enoent ENOENT: no such file or directory, open '/Users/me/Desktop/jzz/package.json'
npm WARN jzz No description
npm WARN jzz No repository field.
npm WARN jzz No README data
npm WARN jzz No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gui@0.5.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gui@0.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2018-12-19T04_48_51_294Z-debug.log
```
node v11.4.0

**Comment by ledlamp** [comment] 2018-12-19 04:58
As a work-around I downloaded the correct version from https://github.com/yue/yue/releases and put the gui.node into `node_modules`

**Comment by cancerberoSgx** [comment] 2019-09-18 14:13
node 12 seems to be not supported (which is not unusual in binary apps), node 10 will work at least that what I'm doing - using 10

**Comment by w0k3** [comment] 2020-02-17 11:14
I can confirm this issue still exists in 2020, downgrading node to 10.x both works and hurts.

**Comment by zcbenz** [comment] 2020-05-22 12:57
Closing since Node 12 is now supported.

**Closed by zcbenz** 2020-05-22 12:57 UTC

**Comment by gkns** [comment] 2021-12-29 08:20
@zcbenz I am using node `v16.13.1` through `nvm` and have copied gui.node to local node_modules path.
Still getting this error: 

`npm ERR! Failed to install Yue: There is no build for your Node.js version (error 404).`

my package.json contents are:
Does anything here needs an update too?

```
...
"dependencies": {
    "bobolink": "3.0.0",
    "fast-deep-equal": "3.1.3",
    "fetch-yode": "1.x",
    "fs-extra": "9.0.1",
    "gui": "0.8.8",
    "ip": "1.1.5",
    "os-locale": "5.0.0"
  },
  "devDependencies": {
    "yackage": "0.3.x"
  }
}
```

**Comment by gkns** [comment] 2021-12-29 13:47
> 2020

2022 (almost) I have this issue!
I built Yue locally and have a gui.node in my local ./node_modules

But, this didn't work. Then I copied the gui.node to my global node's lib directory, like so:
`/Users/<user>/.nvm/versions/node/v16.13.1/lib/gui.node`

Then it started working. However, I am not sure if the above exactly fixed it.
But just in case if useful for someone.

**Comment by zcbenz** [comment] 2022-01-07 08:49
> "gui": "0.8.8",

This error happened because the specified version does not have a build for Node v16, changing the version to latest should work.
